import {test,expect} from '@playwright/test';
test('chapter expands upward and selected events open evidence in source mode',async({page})=>{
 await page.emulateMedia({reducedMotion:'reduce'});
 await page.goto('/#map');
 const timeline=page.locator('.chapter-timeline');
 const before=(await timeline.boundingBox())!;
 const toggle=page.locator('.timeline-list-toggle');
 await toggle.click();
 await expect(toggle).toHaveAttribute('aria-expanded','true');
 const after=(await timeline.boundingBox())!;
 expect(after.y).toBeLessThan(before.y);
 expect(after.y+after.height).toBeCloseTo(before.y+before.height,0);
 await expect(page.locator('[data-timeline-event]')).toHaveCount(65);
 await page.locator('[data-timeline-event="november-exercise"] button').click();
 await expect(page.locator('#november-exercise')).toHaveAttribute('open','');
 await expect(page.locator('.source-window')).toHaveCount(0);
 await expect(page.locator('.story .inline-citation')).toHaveCount(0);
 await page.getByRole('button',{name:'Read the Source'}).click();
 await page.locator('[data-timeline-event="princeton-exercise"] button').click();
 await expect(page.locator('.viewer-tools')).toContainText('Page 3 / 3');
 await expect(page.getByTestId('source-highlight')).toBeVisible();
 await toggle.click();
 await expect(page.locator('#chapter-events')).toHaveAttribute('inert','');
});
