import {useState} from 'react';
import priorLedger from '../data/units/5th_marines/2nd_battalion/research/leadership-1965.json';
import roadLedger from '../data/units/5th_marines/2nd_battalion/research/leadership-1966.json';
const ledger={entries:[...priorLedger.entries,...roadLedger.entries].sort((a,b)=>a.date.localeCompare(b.date))};
import {eventRecords, type Chapter} from './chronology';
for (const entry of ledger.entries) {
 const event=eventRecords.get(entry.eventId);
 if (!event || event.date.start!==entry.date || !event.sources.some(s=>s.anchorId===entry.anchorId)) throw new Error('Invalid leadership evidence: '+entry.eventId);
}
const roles=['CO','XO','S-1','S-2','S-3','S-4','Motor transport','Liaison','H&S','Echo','Foxtrot','Golf','Hotel'];
const label=(date:string)=>new Date(date+'T00:00:00Z').toLocaleDateString('en-US',{month:'long',day:'numeric',year:'numeric',timeZone:'UTC'});
export function Leadership({chapter,date,onSource}:{chapter:Chapter;date:string;onSource?:(id:string)=>void}) {
 const [selected,setSelected]=useState<string|null>(null);
 const available=(chapter.id===priorLedger.chapterId && date<=chapter.dateEnd) || (chapter.id===roadLedger.chapterId && date<=roadLedger.coverageEnd);
 const records=available?ledger.entries.filter(e=>e.date<=date):[];
 const current=(role:string)=>roadLedger.gaps.some(g=>g.role===role&&date>=g.start&&date<=g.end)?undefined:records.filter(e=>e.role===role).at(-1);
 const history=selected?ledger.entries.filter(e=>e.personId===selected && e.date<=chapter.dateEnd):[];
 const person=history.at(-1);
 const card=(role:string)=>{const entry=current(role);return <li key={role} className={`leadership-node role-${role.toLowerCase()}`} data-leadership-role={role}><button disabled={!entry} onClick={()=>setSelected(current=>current===entry!.personId?null:entry!.personId)} aria-expanded={!!entry&&selected===entry?.personId}><span className="officer-portrait" aria-hidden="true">{entry?entry.name.split(' ').slice(1).map(n=>n[0]).slice(0,2).join(''):'—'}</span><span><small>{role==='CO'?'Commanding officer':role==='XO'?'Executive officer':role==='H&S'?'H&S Company':['Echo','Foxtrot','Golf','Hotel'].includes(role)?role+' Company':role}</small><strong key={entry?.name??'unknown'} className="officer-name">{entry?.name??'Not yet established'}</strong>{entry&&<em>{entry.kind==='snapshot'?'Recorded':'Appointed'} {label(entry.date)}</em>}</span></button></li>;};
 return <section className="leadership-tree" aria-label="Battalion leadership"><p className="leadership-date">{label(date)}</p><p className="leadership-hint">Drag the yellow marker on the timeline to explore leadership changes.</p>{!available&&<p>Leadership records for this period have not been assembled yet.</p>}<ol className="leadership-command">{roles.slice(0,2).map(card)}</ol><h3>Battalion staff</h3><ol className="leadership-branches">{roles.slice(2,8).map(card)}</ol><h3>Company commanders</h3><ol className="leadership-branches">{roles.slice(8).map(card)}</ol><p className="leadership-hint">Names show the latest recorded holder as of this date. Roster dates confirm a position, not its starting date. Circles reserve space for verified portraits.</p>{person&&<aside className="officer-details" aria-label="Selected officer"><h3>{person.name}</h3><h4>Recorded role history</h4>{roadLedger.personNotes.filter(note=>note.personId===selected).map(note=><div className="officer-history-note" key={note.personId}><p>{note.text}</p>{onSource && <p>{note.sources.map((source,index)=><span key={source.anchorId}>{index>0?' · ':''}<button className="inline-citation" onClick={()=>onSource(source.anchorId)}>{source.label}</button></span>)}</p>}</div>)}<ol className="officer-history">{history.map((entry,index)=>{const successor=ledger.entries.find(e=>e.date<=chapter.dateEnd&&e.role===entry.role&&e.date>entry.date&&e.personId!==entry.personId);return <li key={index}><strong>{entry.role} · {entry.name}</strong><p>{onSource ? <button className="inline-citation" onClick={()=>onSource(entry.anchorId)}>{entry.kind==='snapshot'?'Recorded':'Appointed'} {label(entry.date)}</button> : <span>{entry.kind==='snapshot'?'Recorded':'Appointed'} {label(entry.date)}</span>}{entry.date>date?' · After selected date':''}</p>{successor&&<p>{onSource ? <button className="inline-citation" onClick={()=>onSource(successor.anchorId)}>Next recorded holder: {successor.name}, {label(successor.date)}.</button> : <>Next recorded holder: {successor.name}, {label(successor.date)}.</>}</p>}</li>;})}</ol></aside>}</section>;
}
